spring:
  application:
    name: jastodon

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

jastodon:
  owner:
    github-id: 20340265
